version: '3.1'

services:

  ha_bot:
    build: .
    depends_on:
      - ha_db
    environment:
      MODES: bot
      DB_HOST: ha_db
      DB_PORT: 3306
      DB_NAME: test
      DB_USER: root
      DB_PASSWORD: password

  ha_mediahost:
    build: .
    volumes:
      - ./torrents:/var/lib/mysql
    environment:
      MODES: mediahost
      DB_HOST: ha_db
      DB_PORT: 3306
      DB_NAME: test
      DB_USER: root
      DB_PASSWORD: password

  ha_db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8020:3306"